// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynqdSe_31ppI9FPNfy5mZQoHPVT9JIDo',
    appId: '1:136618470176:web:e255ca8c929f2161988545',
    messagingSenderId: '136618470176',
    projectId: 'task-masters-64be2',
    authDomain: 'task-masters-64be2.firebaseapp.com',
    storageBucket: 'task-masters-64be2.appspot.com',
    measurementId: 'G-X98X7LQN29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5OaaIlxNvuJy1dgUDEYkxtqaBVTH-d-g',
    appId: '1:136618470176:android:9088ec651f7a245b988545',
    messagingSenderId: '136618470176',
    projectId: 'task-masters-64be2',
    storageBucket: 'task-masters-64be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApt5r10oXRYgOPZXdJi-59aYmS-sduQxw',
    appId: '1:136618470176:ios:7c7aff111cc4cfd0988545',
    messagingSenderId: '136618470176',
    projectId: 'task-masters-64be2',
    storageBucket: 'task-masters-64be2.appspot.com',
    iosClientId: '136618470176-4lro81u9a4albm1mahb3lvsjefv6vpd3.apps.googleusercontent.com',
    iosBundleId: 'task.masters.application.demo.taskMasters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApt5r10oXRYgOPZXdJi-59aYmS-sduQxw',
    appId: '1:136618470176:ios:7c7aff111cc4cfd0988545',
    messagingSenderId: '136618470176',
    projectId: 'task-masters-64be2',
    storageBucket: 'task-masters-64be2.appspot.com',
    iosClientId: '136618470176-4lro81u9a4albm1mahb3lvsjefv6vpd3.apps.googleusercontent.com',
    iosBundleId: 'task.masters.application.demo.taskMasters',
  );
}
